### ISSUE TITLE
requiresAttributes is not needed for Fargate launch type

### ISSUE THREAD

**Issue by r5b9** [amitrahav/wordpress-AWSecs-fargate--template#1]
https://github.com/amitrahav/wordpress-AWSecs-fargate--template/blob/00274ba1def4f008b854b93ecca307ed91533acb/ops/task-definition.json#L134

> requiresAttributes
>   The container instance attributes required by your task. This field is not valid if you are using the Fargate launch type for your task.

**Comment by amitrahav** [comment]
Thank you!

Removed at [e05bacc](https://github.com/amitrahav/wordpress-AWSecs-fargate--template/commit/e05baccf4c50f061f29d01f530b8db95c90e1e2e)
